server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customers-service
          uri: lb://customers-service
          predicates:
            - Path=/customers/**
        - id: accounts-service
          uri: lb://accounts-service
          predicates:
            - Path=/accounts/**
        - id: transactions-service
          uri: lb://transactions-service
          predicates:
            - Path=/transactions/**